# Global Configuration
namespace: dev

# Application Deployment Configuration
replicaCount: 2

image:
  repository: 716147851058.dkr.ecr.us-east-1.amazonaws.com/musical-volunteer
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Network Ports
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

# External Routing
ingress:
  host: python.dev.example.com

# Auto-scaling & High Availability Bounds
hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

pdb:
  minAvailable: 1
