{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "python-app.fullname" . }}
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "python-app.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "python-app.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "python-app.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

